version: "3.7"

x-environment: &default-environment
  POSTGRES_USER: cj
  POSTGRES_PASSWORD: P@ssw0rd
  POSTGRES_DB: cj

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    environment:
      <<: *default-environment
      PORT: 3000
    ports:
      - 3000:3000
    volumes:
      - ..:/workspace
    user: cj
    command: sleep infinity
  db:
    image: postgres:12
    restart: unless-stopped
    environment: *default-environment
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data
      - ../postgresql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

volumes:
  data:
